### PETICIONES PARA TABLA PRODUCTOS
### MOSTRAR PRODUCTOS
GET http://localhost:3000/productos/getProductos



### PETICIONES PARA TABLA USUARIOS
### LOGUEARME
POST http://localhost:3000/usuarios/VerificarUsuario
Content-Type: application/json

{
    "usuario": "juanjose@admin.com",
    "clave": "juanjose"
}

### MOSTRAR TODOS LOS USUARIOS
GET http://localhost:3000/usuarios/getUsuarios
Cookie:  token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc3VhcmlvSWQiOjgsIlJvbCI6ImFkbWluaXN0cmFkb3IiLCJOb21icmVzIjoiSnVhbiBKb3NlIiwiaWF0IjoxNzIzMjQwNTEyLCJleHAiOjE3MjMzMjY5MTJ9.kfQSPm2FzQmdOuSoCNyrFXDEh2Pz4AgTfBiIhq1X_Ds

### AGREGAR USUARIO
POST http://localhost:3000/usuarios/createUsuario
Cookie:  token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc3VhcmlvSWQiOjgsIlJvbCI6ImFkbWluaXN0cmFkb3IiLCJOb21icmVzIjoiSnVhbiBKb3NlIiwiaWF0IjoxNzIzMjQwNTEyLCJleHAiOjE3MjMzMjY5MTJ9.kfQSPm2FzQmdOuSoCNyrFXDEh2Pz4AgTfBiIhq1X_Ds
Content-Type: application/json

{
    "nombres": "Usuario",
    "apellidos": "Prueba eliminación",
    "rol": "cliente",
    "correo": "userprueba@cliente.com",
    "clave": "user"
    
}

### ACTUALIZAR INFO BASICA USUARIO
PUT http://localhost:3000/usuarios/updateInfoUsuario/IuQaXJER2NSGIYSv6OsK
Cookie:  token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc3VhcmlvSWQiOjgsIlJvbCI6ImFkbWluaXN0cmFkb3IiLCJOb21icmVzIjoiSnVhbiBKb3NlIiwiaWF0IjoxNzIzMjQwNTEyLCJleHAiOjE3MjMzMjY5MTJ9.kfQSPm2FzQmdOuSoCNyrFXDEh2Pz4AgTfBiIhq1X_Ds
Content-Type: application/json

{
    "nombres": "Jose Luis",
    "apellidos": "Marin",
    "rol": "cliente"
}

### ACTUALIZAR INFO ACCESO USUARIO
PUT http://localhost:3000/usuarios/updateInfoAccesoUsuario/RQQLBwe47qR4oGowujmO
Cookie:  token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc3VhcmlvSWQiOjgsIlJvbCI6ImFkbWluaXN0cmFkb3IiLCJOb21icmVzIjoiSnVhbiBKb3NlIiwiaWF0IjoxNzIzMjQwNTEyLCJleHAiOjE3MjMzMjY5MTJ9.kfQSPm2FzQmdOuSoCNyrFXDEh2Pz4AgTfBiIhq1X_Ds
Content-Type: application/json

{
    "correo": "lizz@cliente.com",
    "clave": "lizz"
}

### ELIMINAR USUARIO
DELETE http://localhost:3000/usuarios/deleteUsuario/R11vuNdOt8OpBtrROANT
Cookie:  token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc3VhcmlvSWQiOjgsIlJvbCI6ImFkbWluaXN0cmFkb3IiLCJOb21icmVzIjoiSnVhbiBKb3NlIiwiaWF0IjoxNzIzMjQwNTEyLCJleHAiOjE3MjMzMjY5MTJ9.kfQSPm2FzQmdOuSoCNyrFXDEh2Pz4AgTfBiIhq1X_Ds