### |---------------------------------------------------------------|
### |---------------------------------------------------------------|

### PETICIONES HTTP PARA Usuarios
### Traer todos los usuarios
GET http://localhost:3003/usuarios/getUsuarios

### Traer usuario por id
GET http://localhost:3003/usuarios/getUsuario/5

### Traer usuario que sea mesero
GET http://localhost:3003/usuarios/getMeseros

### Crear un Usuario
POST http://localhost:3003/usuarios/createUsuario
Content-Type: application/json

{
    "Cedula": "1120465721",
    "Nombres": "Karol",
    "Apellidos": "Diaz Diaz",
    "TipoUsuario": "Mesero"
}

### Actualizar un Usuario
PUT http://localhost:3003/usuarios/updateUsuario/9
Content-Type: application/json

{
    "Nombres": "Sofia Andrea",
    "Apellidos": "Diaz"
}

### Eliminar un Usuario
DELETE http://localhost:3003/usuarios/deleteUsuario/8


### |---------------------------------------------------------------|
### |---------------------------------------------------------------|

### PETICIONES HTTP PARA Mesas
### Traer todas las mesas
GET http://localhost:3003/mesas/getMesas

### Crear una Mesa
POST http://localhost:3003/mesas/createMesa


### Asignar Mesa a Usuario Tipo Mesero
POST http://localhost:3003/mesas/asignarMesa/
Content-Type: application/json

{
    "MesaId": 20,
    "MeseroId": 3
}

### Quitar el mesero asignado a la mesa y dejar la mesa sin un mesero encargado 
PUT http://localhost:3003/mesas/desasignarMesa
Content-Type: application/json

{
    "MesaId": 20
}

### Liberar la mesa, dejando la cantidad de clientes en 0
PUT http://localhost:3003/mesas/liberarMesa
Content-Type: application/json

{
    "MesaId": 20,
    "MsroId": 3
}

### |---------------------------------------------------------------|
### |---------------------------------------------------------------|

### PETICIONES HTTP PARA DETALLEMESASMESEROS
### Actualizar la cantidad de clientes en una mesa
PUT http://localhost:3003/mesas/updateCantidadClientes

### |---------------------------------------------------------------|
### |---------------------------------------------------------------|

### PETICIONES HTTP PARA PEDIDOS
### Obetener todos los pedidos
GET http://localhost:3003/pedidos/getPedidos

### Obtener el pedido de una mesa mandando el id de la mesa
GET http://localhost:3003/pedidos/getPedidosXMesaId/20



### |---------------------------------------------------------------|
### |---------------------------------------------------------------|


### PETICIONS HTTP PARA PRODUCTOS
### Obtener los productos
GET http://localhost:3003/productos/getProductos

### Obtener un producto por id
GET http://localhost:3003/productos/getProducto/2

### Crear un Producto
POST http://localhost:3003/productos/createProducto
Content-Type: application/json

{
    "Nombre": "Pizza Mexicana",
    "Descripcion": "Pizza con maiz y carne molida para 4 personas",
    "Precio": 33000,
    "Categoria": "Comida"
}

### Actualizar un Producto
PUT http://localhost:3003/productos/updateProducto/112
Content-Type: application/json

{
    "Nombre": "Costillas BBQ",
    "Descripcion": "12 costillas BBQ para 4 personas",
    "Precio": 35000
}
